### ISSUE TITLE
Feature: Open discussions page for project?

### ISSUE THREAD

**Issue by Grntrenchman** [CodedBeats/Automation#4]
Noticed the note in the changelogs.
Maybe [enable discussions tab](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) for communication? Otherwise here works.

Note:
Hey, thanks.

That fix took 2 people here, probably why it's so "elegant". I couldn't figure out all of it (logic that ones next to each other in index were possibly already matched) and bounced it off someone (who got the logic of first selection always being odd). I'm guessing you were thinking what I was going to do at first, a static array of "bad matches", ie. [1,3,5] [2,4,6]...

No worries about the random, as it's to taste.
I'm just paranoid of game devs watching/tracking easy to catch things, and 1 click exactly every 0.4 sec is a blinding beacon imo.

I'm thinking of redoing this portion to be more natural anyway, but not sure of the runtime impact, the matching seems to be the slow bit, and to do what I want, it'd be comparing the tiles *every* time it scanned a new one after the first. But I'm also of the mind that even a massive slowdown in processing will be worth a much lower chance of detectability, and then it would also work in other games that don't give you as many "misses".

**Comment by CodedBeats** [comment]
_left response in newly created discussion :3_
